/**
 * cnn-scorer.test.js — minisplice vi2-7k 1D-CNN port (Phase 2).
 *
 * Validation has three independent layers:
 *  1. JS ≡ numpy reference — every golden vector (generated by extract_cnn.py from
 *     the CC0 weights) must reproduce, per layer, the reference forward pass.
 *  2. structural — the bundled model decodes to the exact 7026-parameter shape.
 *  3. behavioral/biological — a canonical donor/acceptor consensus must score far
 *     above random background and above a broken-GT core (independent of the
 *     reference code path: a transposed/un-flipped model could not pass this).
 */
import { describe, it, expect } from 'vitest';
import golden from './fixtures/cnn-golden.json';
import {
  CNN_LEN,
  cnnForwardDebug,
  cnnSiteProb,
  cnnSiteScore,
  scoreSpliceSitesCNN,
} from '../cnn-scorer.js';

const BASES = 'ACGT';
const toWindow = (s) => Int8Array.from([...s].map((c) => BASES.indexOf(c)));

const near = (a, b, abs) => Math.abs(a - b) <= abs;

describe('CNN forward — JS ≡ numpy reference (golden vectors)', () => {
  it('reproduces every layer of the reference forward pass', () => {
    expect(golden.vectors.length).toBeGreaterThanOrEqual(7);
    for (const v of golden.vectors) {
      expect(v.seq.length).toBe(CNN_LEN);
      const d = cnnForwardDebug(toWindow(v.seq));
      // layer fingerprints (sums are O(10²) → abs 1e-2 is very safe for f64-vs-f64)
      expect(near(d.conv1_sum, v.conv1_sum, 1e-2)).toBe(true);
      expect(near(d.pool1_sum, v.pool1_sum, 1e-2)).toBe(true);
      expect(near(d.conv2_sum, v.conv2_sum, 1e-2)).toBe(true);
      expect(near(d.pool2_sum, v.pool2_sum, 1e-2)).toBe(true);
      expect(near(d.dense_sum, v.dense_sum, 1e-2)).toBe(true);
      expect(near(d.logit1, v.logit1, 2e-3)).toBe(true);
      expect(near(d.P, v.P, 1e-4)).toBe(true);
      // calibrated score lookup matches too
      expect(near(cnnSiteScore(d.P), v.score, 1e-3)).toBe(true);
      expect(near(cnnSiteProb(toWindow(v.seq)), v.P, 1e-4)).toBe(true);
    }
  });
});

describe('CNN — behavioral / biological anchor', () => {
  const P = (label) => {
    const v = golden.vectors.find((x) => x.label === label);
    return cnnSiteProb(toWindow(v.seq));
  };
  it('canonical donor consensus scores far above random background', () => {
    const consensus = P('donor_consensus');
    const maxRandom = Math.max(
      ...golden.vectors.filter((v) => v.kind === 'random').map((v) => cnnSiteProb(toWindow(v.seq)))
    );
    expect(consensus).toBeGreaterThan(0.9);
    expect(consensus).toBeGreaterThan(maxRandom * 10);
  });
  it('breaking the GT core collapses the donor probability', () => {
    expect(P('donor_consensus')).toBeGreaterThan(P('donor_brokenGT'));
    expect(P('donor_brokenGT')).toBeLessThan(0.1);
  });
  it('canonical acceptor consensus scores high', () => {
    expect(P('acceptor_consensus')).toBeGreaterThan(0.5);
  });
});

describe('CNN — calibration table', () => {
  it('maps a near-certain probability near the top of the odds-ratio range', () => {
    expect(cnnSiteScore(0.99)).toBeGreaterThan(10);
  });
  it('maps a near-zero probability to a strongly negative score', () => {
    expect(cnnSiteScore(0.001)).toBeLessThan(-5);
  });
  it('is monotonic non-decreasing in probability', () => {
    let prev = -Infinity;
    for (let p = 0; p <= 1.0001; p += 0.02) {
      const s = cnnSiteScore(Math.min(p, 0.999));
      expect(s).toBeGreaterThanOrEqual(prev - 1e-9);
      prev = s;
    }
  });
});

describe('scoreSpliceSitesCNN — same interface as the PWM scorer', () => {
  it('finds a planted donor at the G of GT with a high calibrated score', () => {
    const seq = golden.vectors.find((v) => v.label === 'donor_consensus').seq;
    const { donors, acceptors } = scoreSpliceSitesCNN(seq);
    // the planted GT sits at index 100 (window centre) with full 202bp context
    const hit = donors.find((d) => d.pos === 100);
    expect(hit).toBeTruthy();
    expect(hit.score).toBeGreaterThan(10);
    // shape contract
    expect(Array.isArray(donors)).toBe(true);
    expect(Array.isArray(acceptors)).toBe(true);
    for (const d of [...donors, ...acceptors]) {
      expect(typeof d.pos).toBe('number');
      expect(typeof d.score).toBe('number');
    }
  });

  it('omits sites without full 202bp context (matches upstream skip)', () => {
    // a short sequence has no site with 100bp flanks on both sides
    const { donors, acceptors } = scoreSpliceSitesCNN('ACGTAGGTACGTAG');
    expect(donors.length).toBe(0);
    expect(acceptors.length).toBe(0);
  });

  it('reports an acceptor at the G of AG', () => {
    const seq = golden.vectors.find((v) => v.label === 'acceptor_consensus').seq;
    const { acceptors } = scoreSpliceSitesCNN(seq);
    const hit = acceptors.find((a) => a.pos === 101); // AG at [100,101] → G at 101
    expect(hit).toBeTruthy();
    expect(hit.score).toBeGreaterThan(3);
  });
});
