/**
 * gene-parser.test.js — frame-aware gene parser on real multi-intron genes.
 *
 * The per-intron greedy decoder merges closely-spaced short introns; the parser
 * threads the reading frame (content-first: maximise the clean coding ORF via
 * GT-AG introns) and recovers them. Ground truth: T. reesei cbh1 (2 introns) and
 * A. niger glaA (4 short introns, fungal — the vertebrate CNN under-scores their
 * acceptors, which is why donors land exactly but one weak acceptor is ±~10 bp).
 */
import { describe, it, expect } from 'vitest';
import { parseGeneBothStrands, ORGANISM_PRESETS } from '../gene-parser.js';
import { scoreSpliceSitesCNN } from '../cnn-scorer.js';
import { reverseComplement } from '../../../sequence-utils.js';

const FUNGI = ORGANISM_PRESETS.fungi;
const run = (seq) => parseGeneBothStrands(seq, scoreSpliceSitesCNN, reverseComplement, FUNGI);

const CBHI =
  'ATGTATCGGAAGTTGGCCGTCATCTCGGCCTTCTTGGCCACAGCTCGTGCTCAGTCGGCCTGCACTCTCCAATCGGAGACTCACCCGCCTCTGACATGGCAGAAATGCTCGTCTGGTGGCACGTGCACTCAACAGACAGGCTCCGTGGTCATCGACGCCAACTGGCGCTGGACTCACGCTACGAACAGCAGCACGAACTGCTACGATGGCAACACTTGGAGCTCGACCCTATGTCCTGACAACGAGACCTGCGCGAAGAACTGCTGTCTGGACGGTGCCGCCTACGCGTCCACGTACGGAGTTACCACGAGCGGTAACAGCCTCTCCATTGGCTTTGTCACCCAGTCTGCGCAGAAGAACGTTGGCGCTCGCCTTTACCTTATGGCGAGCGACACGACCTACCAGGAATTCACCCTGCTTGGCAACGAGTTCTCTTTCGATGTTGATGTTTCGCAGCTGCCGTAAGTGACTTACCATGAACCCCTGACGCTATCTTCTTGTTGGCTCCCAGCTGACTGGCCAATTCAAGGTGCGGCTTGAACGGAGCTCTCTACTTCGTGTCCATGGACGCGGATGGTGGCGTGAGCAAGTATCCCACCAACACCGCTGGCGCCAAGTACGGCACGGGGTACTGTGACAGCCAGTGTCCCCGCGATCTGAAGTTCATCAATGGCCAGGCCAACGTTGAGGGCTGGGAGCCGTCATCCAACAACGCGAACACGGGCATTGGAGGACACGGAAGCTGCTGCTCTGAGATGGATATCTGGGAGGCCAACTCCATCTCCGAGGCTCTTACCCCCCACCCTTGCACGACTGTCGGCCAGGAGATCTGCGAGGGTGATGGGTGCGGCGGAACTTACTCCGATAACAGATATGGCGGCACTTGCGATCCCGATGGCTGCGACTGGAACCCATACCGCCTGGGCAACACCAGCTTCTACGGCCCTGGCTCAAGCTTTACCCTCGATACCACCAAGAAATTGACCGTTGTCACCCAGTTCGAGACGTCGGGTGCCATCAACCGATACTATGTCCAGAATGGCGTCACTTTCCAGCAGCCCAACGCCGAGCTTGGTAGTTACTCTGGCAACGAGCTCAACGATGATTACTGCACAGCTGAGGAGGCAGAATTCGGCGGATCCTCTTTCTCAGACAAGGGCGGCCTGACTCAGTTCAAGAAGGCTACCTCTGGCGGCATGGTTCTGGTCATGAGTCTGTGGGATGATGTGAGTTTGATGGACAAACATGCGCGTTGACAAAGAGTCAAGCAGCTGACTGAGATGTTACAGTACTACGCCAACATGCTGTGGCTGGACTCCACCTACCCGACAAACGAGACCTCCTCCACACCCGGTGCCGTGCGCGGAAGCTGCTCCACCAGCTCCGGTGTCCCTGCTCAGGTCGAATCTCAGTCTCCCAACGCCAAGGTCACCTTCTCCAACATCAAGTTCGGACCCATTGGCAGCACCGGCAACCCTAGCGGCGGCAACCCTCCCGGCGGAAACCCGCCTGGCACCACCACCACCCGCCGCCCAGCCACTACCACTGGAAGCTCTCCCGGACCTACCCAGTCTCACTACGGCCAGTGCGGCGGTATTGGCTACAGCGGCCCCACGGTCTGCGCCAGCGGCACAACTTGCCAGGTCCTGAACCCTTACTACTCTCAGTGCCTGTAA';

const GLAA =
  'ATGTCGTTCCGATCTCTACTCGCCCTGAGCGGCCTCGTCTGCACAGGGTTGGCAAATGTGATTTCCAAGCGCGCGACCTTGGATTCATGGTTGAGCAACGAAGCGACCGTGGCTCGTACTGCCATCCTGAATAACATCGGGGCGGACGGTGCTTGGGTGTCGGGCGCGGACTCTGGCATTGTCGTTGCTAGTCCCAGCACGGATAACCCGGACTGTATGTTTCGAGCTCAGATTTAGTATGAGTGTGTCATTGATTGATTGATGCTGACTGGCGTGTCGTTTGTTGTAGACTTCTACACCTGGACTCGCGACTCTGGTCTCGTCCTCAAGACCCTCGTCGATCTCTTCCGAAATGGAGATACCAGTCTCCTCTCCACCATTGAGAACTACATCTCCGCCCAGGCAATTGTCCAGGGTATCAGTAACCCCTCTGGTGATCTGTCCAGCGGCGCTGGTCTCGGTGAACCCAAGTTCAATGTCGATGAGACTGCCTACACTGGTTCTTGGGGACGGCCGCAGCGAGATGGTCCGGCTCTGAGAGCAACTGCTATGATCGGCTTCGGGCAGTGGCTGCTTGTATGTTCTCCACCCCCTTGCGTCTGATCTGTGACATATGTAGCTGACTGGTCAGGACAATGGCTACACCAGCACCGCAACGGACATTGTTTGGCCCCTCGTTAGGAACGACCTGTCGTATGTGGCTCAATACTGGAACCAGACAGGATATGGTGTGTTTGTTTTATTTTAAATTTCCAAAGATGCGCCAGCAGAGCTAACCCGCGATCGCAGATCTCTGGGAAGAAGTCAATGGCTCGTCTTTCTTTACGATTGCTGTGCAACACCGCGCCCTTGTCGAAGGTAGTGCCTTCGCGACGGCCGTCGGCTCGTCCTGCTCCTGGTGTGATTCTCAGGCACCCGAAATTCTCTGCTACCTGCAGTCCTTCTGGACCGGCAGCTTCATTCTGGCCAACTTCGATAGCAGCCGTTCCGGCAAGGACGCAAACACCCTCCTGGGAAGCATCCACACCTTTGATCCTGAGGCCGCATGCGACGACTCCACCTTCCAGCCCTGCTCCCCGCGCGCGCTCGCCAACCACAAGGAGGTTGTAGACTCTTTCCGCTCAATCTATACCCTCAACGATGGTCTCAGTGACAGCGAGGCTGTTGCGGTGGGTCGGTACCCTGAGGACACGTACTACAACGGCAACCCGTGGTTCCTGTGCACCTTGGCTGCCGCAGAGCAGTTGTACGATGCTCTATACCAGTGGGACAAGCAGGGGTCGTTGGAGGTCACAGATGTGTCGCTGGACTTCTTCAAGGCACTGTACAGCGATGCTGCTACTGGCACCTACTCTTCGTCCAGTTCGACTTATAGTAGCATTGTAGATGCCGTGAAGACTTTCGCCGATGGCTTCGTCTCTATTGTGGTAAGTCTACGCTAGACAAGCGCTCATGTTGACAGAGGGTGCGTACTAACAGAAGTAGGAAACTCACGCCGCAAGCAACGGCTCCATGTCCGAGCAATACGACAAGTCTGATGGCGAGCAGCTTTCCGCTCGCGACCTGACCTGGTCTTATGCTGCTCTGCTGACCGCCAACAACCGTCGTAACTCCGTCGTGCCTGCTTCTTGGGGCGAGACCTCTGCCAGCAGCGTGCCCGGCACCTGTGCGGCCACATCTGCCATTGGTACCTACAGCAGTGTGACTGTCACCTCGTGGCCGAGTATCGTGGCTACTGGCGGCACCACTACGACGGCTACCCCCACTGGATCCGGCAGCGTGACCTCGACCAGCAAGACCACCGCGACTGCTAGCAAGACCAGCACCAGTACGTCATCAACCTCCTGTACCACTCCCACCGCCGTGGCTGTGACTTTCGATCTGACAGCTACCACCACCTACGGCGAGAACATCTACCTGGTCGGATCGATCTCTCAGCTGGGTGACTGGGAAACCAGCGACGGCATAGCTCTGAGTGCTGACAAGTACACTTCCAGCGACCCGCTCTGGTATGTCACTGTGACTCTGCCGGCTGGTGAGTCGTTTGAGTACAAGTTTATCCGCATTGAGAGCGATGACTCCGTGGAGTGGGAGAGTGATCCCAACCGAGAATACACCGTTCCTCAGGCGTGCGGAACGTCGACCGCGACGGTGACTGACACCTGGCGGTAGACAATCAA';

const randDna = (seed, n) => {
  let x = seed >>> 0; let s = '';
  for (let i = 0; i < n; i++) { x = (1103515245 * x + 12345) & 0x7fffffff; s += 'ACGT'[(x >> 16) & 3]; }
  return s;
};

describe('frame-aware gene parser — real fungal genes', () => {
  it('recovers both cbh1 introns exactly', () => {
    const r = run(CBHI);
    expect(r.strand).toBe(1);
    expect(r.introns.map((i) => [i.start, i.end])).toEqual([[461, 529], [1226, 1289]]);
  });

  it('returns the CDS span (cdsStart/cdsEnd) enclosing every intron', () => {
    const r = run(CBHI);
    expect(r.cdsStart).toBe(0); // cbh1 begins at the leading ATG
    expect(r.cdsEnd).toBeGreaterThan(1289); // past the second intron
    expect(r.cdsEnd).toBeLessThanOrEqual(CBHI.length);
    for (const it of r.introns) {
      expect(it.start).toBeGreaterThanOrEqual(r.cdsStart);
      expect(it.end).toBeLessThanOrEqual(r.cdsEnd);
    }
  });

  it('recovers all four glaA introns — donors exact, weak-acceptor I2 within tolerance', () => {
    const r = run(GLAA);
    expect(r.strand).toBe(1);
    expect(r.introns).toHaveLength(4);
    // donors (intron starts) are detected exactly
    expect(r.introns.map((i) => i.start)).toEqual([214, 576, 728, 1427]);
    // I1/I3/I4 acceptors exact
    expect(r.introns[0].end).toBe(289);
    expect(r.introns[2].end).toBe(789);
    expect(r.introns[3].end).toBe(1485);
    // I2 acceptor is the fungal weak acceptor the vertebrate CNN scores negative;
    // the content model lands it within ~15 bp of the true 631.
    expect(r.introns[1].end).toBeGreaterThan(600);
    expect(r.introns[1].end).toBeLessThanOrEqual(635);
  });

  // SPECIFICITY LIMITATION (documented, not asserted): a SIGNAL-only gene model
  // (splice sites + coding length, NO trained hexamer content model) cannot
  // perfectly reject non-coding DNA — a chance GT-AG pair on random DNA can
  // out-score a real gene's weakest intron. The parser is therefore meant to run
  // on a SELECTED gene region (ATG…stop the user picked), not be swept over whole
  // plasmids; clean rejection of non-coding DNA needs a trained content model.
  // Here we only smoke-test that it returns a valid, bounded structure on random
  // input without throwing.
  it('returns a valid bounded structure on random DNA without throwing', () => {
    for (const seed of [7, 99, 1234, 5]) {
      const r = run(randDna(seed, 3000));
      expect(Array.isArray(r.introns)).toBe(true);
      expect(r.introns.length).toBeLessThan(8);
      for (const it of r.introns) expect(it.end).toBeGreaterThan(it.start);
    }
  });
});
